language: crystal

# Uncomment the following if you'd like Travis to run specs and check code formatting
script:
   - crystal ./spec_sam.cr -- db:migration
   - crystal tool format --check
   - crystal spec
